# Generated by Django 2.2 on 2022-11-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('tema', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Conteudo',
                'verbose_name_plural': 'Conteudos',
            },
        ),
        migrations.CreateModel(
            name='TopicoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.TextField(blank=True)),
                ('index', models.IntegerField()),
                ('tamanho', models.IntegerField()),
                ('folha_index', models.IntegerField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConteudoModel')),
            ],
            options={
                'verbose_name': 'Topico',
                'verbose_name_plural': 'Topicos',
            },
        ),
        migrations.CreateModel(
            name='SubtemaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtema', models.TextField(blank=True)),
                ('index', models.IntegerField()),
                ('tamanho', models.IntegerField()),
                ('folha_index', models.IntegerField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConteudoModel')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
            },
        ),
        migrations.CreateModel(
            name='ImportanteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importate', models.TextField(blank=True)),
                ('index', models.IntegerField()),
                ('tamanho', models.IntegerField()),
                ('folha_index', models.IntegerField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConteudoModel')),
            ],
            options={
                'verbose_name': 'Importante',
                'verbose_name_plural': 'Importantes',
            },
        ),
        migrations.CreateModel(
            name='DestaqueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque', models.TextField(blank=True)),
                ('index', models.IntegerField()),
                ('tamanho', models.IntegerField()),
                ('folha_index', models.IntegerField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConteudoModel')),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
            },
        ),
    ]
