# Generated by Django 2.2 on 2022-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudomodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
